### ISSUE TITLE
Rejected bad transaction

### ISSUE THREAD

**Issue by sunnyk56** [informalsystems/tm-load-test#103]
Hi,
I am trying to use the tm-load-test tool for Benchmarking.
I have tried to use it in Standalone Mode as well as Master/Slave Mode using the command as given below:

 In standalone mode
tm-load-test -c 1 -T 10 -r 1000 -s 250 \
    --broadcast-tx-method async \
    --endpoints ws://tm-endpoint1.somewhere.com:26657/websocket,ws://tm-endpoint2.somewhere.com:26657/websocket \
    --stats-output /path/to/save/stats.csv

 From the master in master/slave mode
tm-load-test \
    master \
    --expect-slaves 2 \
    --bind localhost:26670 \
    -c 1 -T 10 -r 1000 -s 250 \
    --broadcast-tx-method async \
    --endpoints ws://tm-endpoint1.somewhere.com:26657/websocket,ws://tm-endpoint2.somewhere.com:26657/websocket \
    --stats-output /path/to/save/stats.csv
    
 and output in CSV file and the output look like
Parameter,Value,Units
total_time,303.001,seconds
total_txs,2686979,count
total_bytes,671868750,bytes
avg_tx_rate,8867.889417,transactions per second
avg_data_rate,2217381.593975,bytes per second

I have checked the validator logs of these validator nodes there are some error logs 

9:40AM INF WSJSONRPC method=broadcast_tx_async module=rpc-server protocol=websocket remote={"IP":"162.243.168.129","Port":39866,"Zone":""}
9:40AM INF Rejected bad transaction err=null module=mempool peerID= res={"check_tx":{"code":2,"codespace":"sdk","data":null,"events":[],"gas_used":"10572042","gas_wanted":"0","info":"","log":"errUnknownField "tx.TxRaw": {TagNum: 10, WireType:"end_group"}: tx parse error"}} tx="\\x1fQ?mPm\x02)}?????,???Z?P\x13?????m?Z"
9:40AM INF WSJSONRPC method=broadcast_tx_async module=rpc-server protocol=websocket remote={"IP":"162.243.168.129","Port":39866,"Zone":""}
9:40AM INF Rejected bad transaction err=null module=mempool peerID= res={"check_tx":{"code":2,"codespace":"sdk","data":null,"events":[],"gas_used":"10578516","gas_wanted":"0","info":"","log":"errUnknownField "tx.TxRaw": {TagNum: 10, WireType:"end_group"}: tx parse error"}} tx="?d\t\x19-#??.s??UB??P??6}\n\x14Il??/????"
9:40AM INF WSJSONRPC method=broadcast_tx_async module=rpc-server protocol=websocket remote={"IP":"162.243.168.129","Port":39866,"Zone":""}
9:40AM INF Rejected bad transaction err=null module=mempool peerID= res={"check_tx":{"code":2,"codespace":"sdk","data":null,"events":[],"gas_used":"10584990","gas_wanted":"0","info":"","log":"errUnknownField "tx.TxRaw": {TagNum: 10, WireType:"end_group"}: tx parse error"}} tx="?v=?J??\x15????e\x19$??O\x06J/?\x01q?}?\x10"

Please help me solve the issue.

> 

>

**Comment by puneet166** [comment]
@thanethomson @greg-szabo @marbar3778 .Please help ,i am also facing the same issue.

**Comment by thanethomson** [comment]
What ABCI apps are you using? And did you write a [custom client](https://github.com/informalsystems/tm-load-test/blob/master/pkg/loadtest/README.md)?

**Comment by puneet166** [comment]
@thanethomson  Thanks for your response . i have a setup of cosmos node using this repo  https://github.com/althea-net/cosmos-gravity-bridge and trying to test it with TM-load-test. so   i am running this below command - In standalone mode
```
 tm-load-test -c 1 -T 10 -r 1000 -s 250 \
--broadcast-tx-method async \
--endpoints ws://myIP:26657/websocket
 ```

error coming on cosmos side -

9:40AM INF WSJSONRPC method=broadcast_tx_async module=rpc-server protocol=websocket remote={"IP":"162.243.168.129","Port":39866,"Zone":""}
9:40AM INF Rejected bad transaction err=null module=mempool peerID= res={"check_tx":{"code":2,"codespace":"sdk","data":null,"events":[],"gas_used":"10572042","gas_wanted":"0","info":"","log":"errUnknownField "tx.TxRaw": {TagNum: 10, WireType:"end_group"}: tx parse error"}} tx="\x1fQ?mPm\x02)}?????,???Z?P\x13?????m?Z"
9:40AM INF WSJSONRPC method=broadcast_tx_async module=rpc-server protocol=websocket remote={"IP":"162.243.168.129","Port":39866,"Zone":""}
9:40AM INF Rejected bad transaction err=null module=mempool peerID= res={"check_tx":{"code":2,"codespace":"sdk","data":null,"events":[],"gas_used":"10578516","gas_wanted":"0","info":"","log":"errUnknownField "tx.TxRaw": {TagNum: 10, WireType:"end_group"}: tx parse error"}} tx="?d\t\x19-#??.s??UB??P??6}\n\x14Il??/????"
9:40AM INF WSJSONRPC method=broadcast_tx_async module=rpc-server protocol=websocket remote={"IP":"162.243.168.129","Port":39866,"Zone":""}
9:40AM INF Rejected bad transaction err=null module=mempool peerID= res={"check_tx":{"code":2,"codespace":"sdk","data":null,"events":[],"gas_used":"10584990","gas_wanted":"0","info":"","log":"errUnknownField "tx.TxRaw": {TagNum: 10, WireType:"end_group"}: tx parse error"}} tx="?v=?J??\x15????e\x19$??O\x06J/?\x01q?}?\x10"

**Comment by thanethomson** [comment]
So the standard implementation of `tm-load-test` won't work if you're testing against a Cosmos node. The only included transaction format in `tm-load-test` is for the key/value store ABCI app (i.e. the key/value store ABCI app running on top of Tendermint), whereas a Cosmos node is [Gaia](https://github.com/cosmos/gaia) running on top of Tendermint. `tm-load-test` is Tendermint-specific, not Cosmos-specific. The format of transactions that `tm-load-test` sends by default is simple byte arrays like `key=value`, which won't be accepted by a Cosmos node.

If you want to test against a Cosmos node, you're going to have to write a [custom client](https://github.com/informalsystems/tm-load-test/blob/master/pkg/loadtest/README.md) that submits transactions in a format that a Cosmos node accepts.

**Comment by puneet166** [comment]
HI @thanethomson Thanks for your valuable response. I'm researching what kind of formats the Cosmos node accepts or how to write custom client for cosmos node . I haven't got anything yet. So can you help me regarding this. it would be commendable

**Comment by puneetsingh166** [comment]
HI @thanethomson Thanks for your valuable response. I'm researching what kind of formats the Cosmos node accepts or how to write custom client for cosmos node . I haven't got anything yet. So can you help me regarding this. it would be commendable

**Comment by thanethomson** [comment]
For that you're going to need to look into the [Cosmos SDK](https://github.com/cosmos/cosmos-sdk/). I'd recommend finding someone in the [Cosmos community](https://v1.cosmos.network/community) to ask.

**Comment by puneetsingh166** [comment]
Hi @thanethomson i have created my custom client for cosmos . And all that transaction is successful. I would like to know if there is a way to check how many transactions have been successful or how many have failed.

**Comment by thanethomson** [comment]
Tendermint exposes a Prometheus endpoint through which you can monitor the total number of transactions that have been committed. See https://docs.tendermint.com/master/nodes/metrics.html

**Comment by melekes** [comment]
Closing as outdated. @sunnyk56  please comment if you're still experiencing this issue.
