### ISSUE TITLE
Using tm-load-test with automated 4 node network via docker

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [informalsystems/tm-load-test#48]
I tried using the standalone loadtest command
 ```
tm-load-test -c 1 -T 10 -r 1000 -s 250 \

    --broadcast-tx-method async \
    --endpoints ws://tm-endpoint1.somewhere.com:26657/websocket,ws://tm-endpoint2.somewhere.com:26657/websocket
```
in a 4 node network deployed using docker. I get a response
`INFO: Connecting to remote endpoints`
And then it halts the process and goes to $prompt. I tried using the commands
`make lint
make test`
instead. But it gives me the following error:
`state/export_test.go:42:6: func `CalcValidatorsKey` is unused (unused)
crypto/secp256k1/secp256k1.go:11:2: SA1019: Package golang.org/x/crypto/ripemd160 is deprecated: RIPEMD-160 is a legacy hash and should not be used for new applications. Also, this package does not and will not provide an optimized implementation. Instead, use a modern hash like SHA-256 (from crypto/sha256).  (staticcheck)
	"golang.org/x/crypto/ripemd160"
	^
node/node.go:9:2: G108: Profiling endpoint is automatically exposed on /debug/pprof (gosec)
	_ "net/http/pprof"
	^
consensus/state.go:1417: line is 122 characters (lll)
		panic(fmt.Sprintf("Failed to write %v msg to consensus wal due to %v. Check your FS and restart the node", endMsg, err))
consensus/wal.go:209: line is 170 characters (lll)
		wal.Logger.Error("WriteSync failed to flush consensus wal. WARNING: may result in creating alternative proposals / votes for the current height iff the node restarted",
p2p/upnp/upnp.go:381:2: naked return in func `AddPortMapping` with 34 lines of code (nakedret)
	return
	^
consensus/types/peer_round_state.go:15:21: struct of size 160 bytes could be of size 152 bytes:
```
struct{
	ProposalBlockPartsHeader	github.com/tendermint/tendermint/types.PartSetHeader,
	StartTime               	time.Time,
	Height                  	int64,
	Round                   	int,
	ProposalBlockParts      	*github.com/tendermint/tendermint/libs/common.BitArray,
	ProposalPOLRound        	int,
	ProposalPOL             	*github.com/tendermint/tendermint/libs/common.BitArray,
	Prevotes                	*github.com/tendermint/tendermint/libs/common.BitArray,
`
What changes should me made so that the tool works with automatically deployed test network too?

**Comment by AkshayaManimaran96** [comment]
Hi, I encountered the same issue with the standalone machine. Were you able to solve it?

**Comment by marbar3778** [comment]
Hey, thank you for opening the issue. You should not need to run linting to make this work. Most of the errors above stem from linting. 

Try running without the linting and everything should pass. I'll close this issue, but join our discord if you have any more questions, we are quicker to respond there. https://discord.gg/P9h8dDV
