### ISSUE TITLE
tm-load-test error

### ISSUE THREAD

**Issue by AkshayaManimaran96** [informalsystems/tm-load-test#50]
Hi, 
     When I try to run the tm-load-test for standalone machine...I get the following error.
`a@a-VirtualBox:~/home/a/src/github.com/tendermint/tendermint/tm-load-test$ tm-load-test -c 1 -T 10 -r 1000 -s 250     --broadcast-tx-method async     --endpoints ws://tm-endpoint1.somewhere.com:26657/websocket,ws://tm-endpoint2.somewhere.com:26657/websocket     --stats-output /path/to/save/stats.csv
INFO[0000] Connecting to remote endpoints                ctx=loadtest
a@a-VirtualBox:~/home/a/src/github.com/tendermint/tendermint/tm-load-test$ sudo make lint
/root/go/bin/golangci-lint run ./...
WARN [runner] Can't run linter goanalysis_metalinter: S1025: failed prerequisites: [(buildir@github.com/interchainio/tm-load-test/pkg/loadtest, inspect@github.com/interchainio/tm-load-test/pkg/loadtest, isgenerated@github.com/interchainio/tm-load-test/pkg/loadtest): analysis skipped: errors in package: [/home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/websockets.go:289:30: cannot use time.Now().Add(s.remoteCloseWaitTimeout) (value of type time.Time) as time.Time value in argument to s.conn.SetReadDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/websockets.go:269:30: cannot use deadline (variable of type time.Time) as time.Time value in argument to s.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/websockets.go:258:29: cannot use deadline (variable of type time.Time) as time.Time value in argument to s.conn.SetReadDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:331:30: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:306:30: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:227:30: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:232:12: cannot use json.RawMessage(paramsJSON) (value of type json.RawMessage) as json.RawMessage value in struct literal /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:169:70: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.WriteControl /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/master.go:442:33: cannot use w (variable of type http.ResponseWriter) as http.ResponseWriter value in argument to upgrader.Upgrade: wrong type for method Header /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/master.go:442:36: cannot use r (variable of type *http.Request) as *http.Request value in argument to upgrader.Upgrade]] 
ERRO Running error: S1025: failed prerequisites: [(buildir@github.com/interchainio/tm-load-test/pkg/loadtest, inspect@github.com/interchainio/tm-load-test/pkg/loadtest, isgenerated@github.com/interchainio/tm-load-test/pkg/loadtest): analysis skipped: errors in package: [/home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/websockets.go:289:30: cannot use time.Now().Add(s.remoteCloseWaitTimeout) (value of type time.Time) as time.Time value in argument to s.conn.SetReadDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/websockets.go:269:30: cannot use deadline (variable of type time.Time) as time.Time value in argument to s.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/websockets.go:258:29: cannot use deadline (variable of type time.Time) as time.Time value in argument to s.conn.SetReadDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:331:30: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:306:30: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:227:30: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.SetWriteDeadline /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:232:12: cannot use json.RawMessage(paramsJSON) (value of type json.RawMessage) as json.RawMessage value in struct literal /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/transactor.go:169:70: cannot use time.Now().Add(connSendTimeout) (value of type time.Time) as time.Time value in argument to t.conn.WriteControl /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/master.go:442:33: cannot use w (variable of type http.ResponseWriter) as http.ResponseWriter value in argument to upgrader.Upgrade: wrong type for method Header /home/a/home/a/src/github.com/tendermint/tendermint/tm-load-test/pkg/loadtest/master.go:442:36: cannot use r (variable of type *http.Request) as *http.Request value in argument to upgrader.Upgrade]] 
make: *** [Makefile:37: lint] Error 3
`
Any help is appreciated.

**Comment by marbar3778** [comment]
Hey, thanks for opening this issue. Sorry for the delay. It seems you are running multiple commands in the above excerpt. Can you retry running solely the command `tm-load-test`.

**Comment by AkshayaManimaran96** [comment]
Hi,
I tried running solely 'tm-load-test' command. And I'm getting the following error.
`xxx@xxx-XPS-8300:/src/github.com/tendermint/tendermint$ tm-load-test
ERRO[0000] expected at least one endpoint to conduct load test against, but found none  ctx=main'

**Comment by marbar3778** [comment]
`tm-load-test -c 1 -T 10 -r 1000 -s 250 \
    --broadcast-tx-method async \
    --endpoints ws://tm-endpoint1.somewhere.com:26657/websocket`

when running the command did you specify an endpoint? similar to this ^^

**Comment by marbar3778** [comment]
will close this issue as its being discussed in discord.
