### ISSUE TITLE
How to set peer node ID

### ISSUE THREAD

**Issue by mamunbond07** [informalsystems/tm-load-test#54]
Hi,
I have built the **tm-load-test** in master node and the copied the binary to two other slaves through SSH and SCP.
In Master I use this script:
>./tm-load-test \
    master \
    --expect-slaves 2 \
    --bind localhost:26656 \
    -c 1 -T 10 -r 1000 -s 250 \
    --broadcast-tx-method async \
    --endpoints 10.138.0.134:26656,10.138.0.122:26656

and in the two slaves(i.e., in 10.138.0.134 and 10.138.0.122) I use this script:
>./tm-load-test slave --master 10.138.0.121:26656

However, they do not get connected. The master and slaves wait forever to get connected.
In master I get this message:
>INFO[0000] Waiting for all slaves to connect and register  ctx=master
INFO[0000] Starting WebSockets server                    ctx=master

In one slave I get this message:
>INFO[0000] Waiting for successful connection to remote master  addr="10.138.0.121:26656" ctx="slave[018da29f808f4d3e851a58a29276b405]"

In another slave I get this:
> INFO[0000] Waiting for successful connection to remote master  addr="10.138.0.121:26656" ctx="slave[a30613c11af84b06a37b25c15eeb7f5e]"

Could you please help me to resolve this?

**Comment by thanethomson** [comment]
The `--endpoints` flag is meant to indicate where the **Tendermint RPC endpoints** are located (not the slaves).

What I'd recommend is to get it working with your Tendermint network in [standalone mode](https://github.com/informalsystems/tm-load-test#standalone-mode) first, and then try to set up a master/slave configuration if you really need it.

**Comment by mamunbond07** [comment]
Hi, Thanks for your response. I have tried the standalone version:
>./tm-load-test -c 1 -T 10 -r 1000 -s 250     --broadcast-tx-method async     --endpoints ws://localhost:26657/websocket

But I get the following output and the test does not begin and exits immediately. 
>INFO[0000] Connecting to remote endpoints                ctx=loadtest

What am I doing wrong here? Please kindly help.

**Comment by melekes** [comment]
Closing as outdated. @mamunbond07 please comment if you're still experiencing this issue.
